# Generated by Django 2.1.2 on 2018-11-06 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamA', models.CharField(max_length=256)),
                ('teamB', models.CharField(max_length=256)),
                ('date', models.DateTimeField(verbose_name='match_date')),
            ],
        ),
        migrations.CreateModel(
            name='RemainingTickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeARemaining', models.IntegerField(default=0)),
                ('typeBRemaining', models.IntegerField(default=0)),
                ('typeCRemaining', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('typeATotal', models.IntegerField(default=0)),
                ('typeBTotal', models.IntegerField(default=0)),
                ('typeCTotal', models.IntegerField(default=0)),
                ('typeAPrice', models.IntegerField(default=0)),
                ('typeBPrice', models.IntegerField(default=0)),
                ('typeCPrice', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('emailId', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='emailId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Buy.User'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='matchId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Buy.Match'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticketType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buy.TicketType'),
        ),
        migrations.AddField(
            model_name='remainingtickets',
            name='stadiumId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buy.Stadium'),
        ),
        migrations.AddField(
            model_name='match',
            name='stadiumId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buy.Stadium'),
        ),
    ]
