# Generated by Django 2.1.2 on 2018-11-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticketType',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='TicketType',
        ),
    ]
