# Generated by Django 2.1.2 on 2018-11-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buy', '0002_auto_20181107_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='name',
            field=models.CharField(default='match', max_length=256),
        ),
    ]
