# Generated by Django 2.1.2 on 2019-02-05 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Buy', '0004_auto_20181112_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remainingtickets',
            name='stadiumId',
        ),
        migrations.AddField(
            model_name='remainingtickets',
            name='matchId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Buy.Match'),
            preserve_default=False,
        ),
    ]
